services:
  - type: web
    name: finance-chatbot
    buildCommand: npm run build
    publishDir: dist
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://finance-chatbot-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
